{{- if .Values.crds.install }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "certManager.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "certManager.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
    {{- include "certManager.defaultLabels" . | nindent 4 }}
    role: "{{ template "certManager.CRDInstallSelector" . }}"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: "{{ template "certManager.name.crdInstall" . }}"
      {{- include "certManager.selectorLabels" . | nindent 6 }}
  # allow egress traffic to the Kubernetes API
  egress:
  - ports:
    - port: 443
      protocol: TCP
    # legacy port kept for compatibility
    - port: 6443
      protocol: TCP
    to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
{{- end }}
